## Monitor rules
## Format: monitorrule=name:<regex>,width:<px>,height:<px>,refresh:<Hz>,x:<px>,y:<px>,scale:<factor>,rr:<transform>,vrr:<0|1>

monitorrule=name:^DP-2$,width:3840,height:2160,refresh:120,x:0,y:0,scale:2,rr:0,vrr:0
